### PR TITLE
libmatemixer: Remove weak pointers on dispose

### LINKED ISSUE #39: heap corruption/crash when pulseaudio audio device is removed
#### Expected behaviour
Using a USB audio device, if the audio device disconnects, MATE software should handle the device removal gracefully.

#### Actual behaviour
If the audio device vanishes, applications which integrate libmatemixer will error or crash. In mate-settings-daemon, the corruption is detected by malloc:
`free(): corrupted unsorted chunks`
`corrupted double-linked list`
`malloc_consolidate(): unaligned fastbin chunk detected`
In mate-volume-control-status-icon, it presents as so:
`malloc(): unaligned tcache chunk detected`
`../glib/glib/gmem.c:207: failed to allocate 103079215112 bytes`

#### Steps to reproduce the behaviour
1. plug in USB audio adapter
2. unplug USB audio adapter

The mate settings daemon backtrace shows the "device-removed" signal being fired and a device name string being removed from a hash table, I think because of on_connection_card_removed, while in mate-volume-control-status-icon, the error seems to occur in pulse_ext_stream_update->g_object_freeze_notify for some reason.

[crashes.tar.gz](https://github.com/mate-desktop/libmatemixer/files/12443450/crashes.tar.gz)

#### MATE general version
1.26.0

#### Package version
1.26.0 (no patches)

#### Linux Distribution
Arch Linux (rolling)

### PR DESCRIPTION
**Pull request by ProMarbler14**
Weak pointers are happily overwriting freed object memory (and newly created structures) whenever a weakly referenced object outlives the object storing the reference. Remove those callbacks when they are no longer needed.

Fixes #39

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
Code looks good, builds and runs fine. Unfortunately I cannot duplicate the crash even by plugging and unplugging a USB sound device, but everything worked and I didn't get any ugly surprises.

If we look at 
https://blogs.gnome.org/mcatanzaro/2022/08/11/common-glib-programming-errors-part-two-weak-pointers/

we have
"Mistake 5: Failure to Disconnect Weak Pointer

In object-oriented languages, weak pointers are a safety improvement. The idea is to hold a non-owning pointer to an object that gets automatically set to NULL when that object is destroyed to prevent use-after-free vulnerabilities. However, this only works well because object-oriented languages have destructors. Without destructors, we have to deregister the weak pointer manually, and failure to do so is a disaster that will result in memory corruption that’s extremely difficult to track down."

Especially note the last two lines: this is EXACTLY what has been reported, and it has caused perhaps five different crashes and has been a blocker to building mate-media with the applet in-process in Fedora. 

THANK YOU!

Calling for further reviews, someone who can duplicate the crash needs to test this

**Comment by raveit65** [comment]
As i am not affected by this bug for myself when plug/unplug a device i can't say if this helps.
In a first runtime test everything seems to work as usual.
I will search for report for this issue and ask for testing this PR.
I can also do a test rpm build for fedora and ask for testing in rhbz.

**Comment by lukefromdc** [comment]
Any updates on testing this? Note that I have kept this installed and haven't had any behavioral changes in recording or playing audio but never got the crash before or after this either

**Comment by raveit65** [comment]
I got positive results from 3 reports at rhbz by a user some days ago, but i wait for a final conformation.
https://bugzilla.redhat.com/show_bug.cgi?id=2223656#c18
https://bugzilla.redhat.com/show_bug.cgi?id=2223657#c18
https://bugzilla.redhat.com/show_bug.cgi?id=2222196#c15

File: libmatemixer/matemixer-stream-control.c [hunk 1]
```diff
@@ -284,6 +286,19 @@ mate_mixer_stream_control_init (MateMixerStreamControl *control)
...
 
+static void
+mate_mixer_stream_control_dispose (GObject *object)
+{
+    MateMixerStreamControl *control;
+
+    control = MATE_MIXER_STREAM_CONTROL (object);
+    if (control->priv->stream != NULL)
+        g_object_remove_weak_pointer(G_OBJECT (control->priv->stream),
+                                     (gpointer *) &control->priv->stream);
```
Comment (cwendling) [inline libmatemixer/matemixer-stream-control.c:297]: This could also be done in the existing `finalize()`, as it's not releasing a reference, but just avoiding the weak pointer from accessing this object's memory after destruction.

This is just a note, it's also fine as it is.

**Review by cwendling — APPROVED** [review]
I cannot test this as I don't have any pluggable device, nor could I ever reproduce this; but on the paper the changes make sense, whether they fix that particular issue or not.

**Review by raveit65 — APPROVED** [review]
LGTM.
I got positive confirmation in 3 related bugreports at rhbz.
No crashes any more since 2 weeks.
I will cherry-pick that to 1.26 branch an do a new release.

**Comment by raveit65** [comment]
@ProMarbler14 
Thanks a lot. Are you interested in maintaining libmatemixer and mate-media?
Those packages are unmaintained since years.
